export default function Benefits() {
      const benefits = [
          {
                title: "Execution Over Ideas",
                      description:
                              "Turn your ideas into real projects instead of leaving them in your notes.",
                                    icon: "🚀",
                                        },
                                            {
                                                  title: "Builder Community",
                                                        description:
                                                                "Build alongside ambitious young creators who keep each other accountable.",
                                                                      icon: "🤝",
                                                                          },
                                                                              {
                                                                                    title: "Daily Momentum",
                                                                                          description:
                                                                                                  "Small daily tasks help you make consistent progress for 14 days.",
                                                                                                        icon: "📈",
                                                                                                            },
                                                                                                                {
                                                                                                                      title: "Portfolio Project",
                                                                                                                            description:
                                                                                                                                    "Finish with something real you can showcase to colleges, competitions, or future teammates.",
                                                                                                                                          icon: "🏆",
                                                                                                                                              },
                                                                                                                                                ];

                                                                                                                                                  return (
                                                                                                                                                      <section id="benefits"
                                                                                                                                                       className="bg-white px-6 py-24">
                                                                                                                                                            <div className="mx-auto max-w-6xl">
                                                                                                                                                                    <div className="text-center">
                                                                                                                                                                              <p className="text-sm font-semibold uppercase tracking-[0.3em] text-orange-500">
                                                                                                                                                                                          WHY JOIN?
                                                                                                                                                                                                    </p>

                                                                                                                                                                                                              <h2 className="mt-4 text-4xl font-bold text-slate-900">
                                                                                                                                                                                                                          What you'll gain
                                                                                                                                                                                                                                    </h2>

                                                                                                                                                                                                                                              <p className="mx-auto mt-6 max-w-2xl text-lg text-slate-600">
                                                                                                                                                                                                                                                          Builder Sprint is designed to help you build momentum—not just motivation.
                                                                                                                                                                                                                                                                    </p>
                                                                                                                                                                                                                                                                            </div>

                                                                                                                                                                                                                                                                                    <div className="mt-16 grid gap-8 md:grid-cols-2">
                                                                                                                                                                                                                                                                                              {benefits.map((benefit) => (
                                                                                                                                                                                                                                                                                                          <div
                                                                                                                                                                                                                                                                                                                        key={benefit.title}
                                                                                                                                                                                                                                                                                                                                      className="rounded-2xl border border-slate-200 p-8 transition hover:border-orange-500 hover:shadow-lg"
                                                                                                                                                                                                                                                                                                                                                  >
                                                                                                                                                                                                                                                                                                                                                                <div className="text-4xl">{benefit.icon}</div>

                                                                                                                                                                                                                                                                                                                                                                              <h3 className="mt-5 text-2xl font-bold text-slate-900">
                                                                                                                                                                                                                                                                                                                                                                                              {benefit.title}
                                                                                                                                                                                                                                                                                                                                                                                                            </h3>

                                                                                                                                                                                                                                                                                                                                                                                                                          <p className="mt-4 leading-7 text-slate-600">
                                                                                                                                                                                                                                                                                                                                                                                                                                          {benefit.description}
                                                                                                                                                                                                                                                                                                                                                                                                                                                        </p>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                    </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                              ))}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                </section>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  );
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  }