"use client";

import { useState } from "react";

const faqs = [
  {
      question: "Who can join Builder Sprint?",
          answer:
                "Anyone who wants to build something real. Students, beginners, and young builders are welcome.",
                  },
                    {
                        question: "Do I need coding experience?",
                            answer:
                                  "No. Builder Sprint focuses on execution. Your project can be technical, creative, or community-based.",
                                    },
                                      {
                                          question: "How much time does it take?",
                                              answer:
                                                    "Around 30–60 minutes per day for 14 days.",
                                                      },
                                                        {
                                                            question: "Is Builder Sprint free?",
                                                                answer:
                                                                      "Yes. The first cohort is completely free.",
                                                                        },
                                                                        ];

                                                                        export default function FAQ() {
                                                                          const [open, setOpen] = useState<number | null>(0);

                                                                            return (
                                                                                <section id="faq" className="bg-slate-50 px-6 py-24">
                                                                                      <div className="mx-auto max-w-4xl">
                                                                                              <div className="text-center">
                                                                                                        <p className="text-sm font-semibold uppercase tracking-[0.3em] text-orange-500">
                                                                                                                    FAQ
                                                                                                                              </p>

                                                                                                                                        <h2 className="mt-4 text-4xl font-bold text-slate-900">
                                                                                                                                                    Frequently Asked Questions
                                                                                                                                                              </h2>
                                                                                                                                                                      </div>

                                                                                                                                                                              <div className="mt-16 space-y-4">
                                                                                                                                                                                        {faqs.map((faq, index) => (
                                                                                                                                                                                                    <div
                                                                                                                                                                                                                  key={faq.question}
                                                                                                                                                                                                                                className="rounded-2xl border border-slate-200 bg-white"
                                                                                                                                                                                                                                            >
                                                                                                                                                                                                                                                          <button
                                                                                                                                                                                                                                                                          onClick={() =>
                                                                                                                                                                                                                                                                                            setOpen(open === index ? null : index)
                                                                                                                                                                                                                                                                                                            }
                                                                                                                                                                                                                                                                                                                            className="flex w-full items-center justify-between p-6 text-left"
                                                                                                                                                                                                                                                                                                                                          >
                                                                                                                                                                                                                                                                                                                                                          <span className="font-semibold text-slate-900">
                                                                                                                                                                                                                                                                                                                                                                            {faq.question}
                                                                                                                                                                                                                                                                                                                                                                                            </span>

                                                                                                                                                                                                                                                                                                                                                                                                            <span className="text-2xl">
                                                                                                                                                                                                                                                                                                                                                                                                                              {open === index ? "−" : "+"}
                                                                                                                                                                                                                                                                                                                                                                                                                                              </span>
                                                                                                                                                                                                                                                                                                                                                                                                                                                            </button>

                                                                                                                                                                                                                                                                                                                                                                                                                                                                          {open === index && (
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          <div className="px-6 pb-6 text-slate-600 leading-7">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            {faq.answer}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          )}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                ))}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  </section>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    );
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    }