export default function Footer() {
          return (
              <footer className="bg-slate-900 px-6 py-12 text-slate-300">
                    <div className="mx-auto max-w-6xl text-center">
                            <h3 className="text-2xl font-bold text-white">
                                      CONTRIBE
                                              </h3>

                                                      <p className="mt-3">
                                                                Build. Participate. Grow.
                                                                        </p>

                                                                                <div className="mt-8 flex flex-wrap justify-center gap-8">
                                                                                          <a
                                                                                                      href="#top"
                                                                                                                  className="transition hover:text-white"
                                                                                                                            >
                                                                                                                                        Builder Sprint
                                                                                                                                                  </a>

                                                                                                                                                            <a
                                                                                                                                                                        href="https://linktr.ee/joincontribe"
                                                                                                                                                                                    target="_blank"
                                                                                                                                                                                                rel="noopener noreferrer"
                                                                                                                                                                                                            className="transition hover:text-white"
                                                                                                                                                                                                                      >
                                                                                                                                                                                                                                  Learn About CONTRIBE
                                                                                                                                                                                                                                            </a>

                                                                                                                                                                                                                                                      <a
                                                                                                                                                                                                                                                                  href="https://www.instagram.com/joincontribe?igsh=MTU3M3h5MG91NnZuZw=="
                                                                                                                                                                                                                                                                              target="_blank"
                                                                                                                                                                                                                                                                                          rel="noopener noreferrer"
                                                                                                                                                                                                                                                                                                      className="transition hover:text-white"
                                                                                                                                                                                                                                                                                                                >
                                                                                                                                                                                                                                                                                                                            Instagram
                                                                                                                                                                                                                                                                                                                                      </a>
                                                                                                                                                                                                                                                                                                                                              </div>

                                                                                                                                                                                                                                                                                                                                                      <div className="mt-10 border-t border-slate-700 pt-8">
                                                                                                                                                                                                                                                                                                                                                                <p>© 2026 CONTRIBE. All rights reserved.</p>

                                                                                                                                                                                                                                                                                                                                                                          <p className="mt-2 text-sm text-slate-400">
                                                                                                                                                                                                                                                                                                                                                                                      Made with ❤️ by{" "}
                                                                                                                                                                                                                                                                                                                                                                                          <a
                                                                                                                                                                                                                                                                                                                                                                                                href="https://www.instagram.com/insightbolt.enquiries?igsh=MWE4Ynh3cThzdmRtYw=="
                                                                                                                                                                                                                                                                                                                                                                                                      target="_blank"
                                                                                                                                                                                                                                                                                                                                                                                                            rel="noopener noreferrer"
                                                                                                                                                                                                                                                                                                                                                                                                                  className="font-medium text-slate-300 transition hover:text-white"
                                                                                                                                                                                                                                                                                                                                                                                                                      >
                                                                                                                                                                                                                                                                                                                                                                                                                            InsightBolt
                                                                                                                                                                                                                                                                                                                                                                                                                                </a>
                                                                                                                                                                                                                                                                                                                                                                                                </p>
                                                                                                                                                                                                                                                                                                                                                                                                        </div>
                                                                                                                                                                                                                                                                                                                                                                                                              </div>
                                                                                                                                                                                                                                                                                                                                                                                                                  </footer>
                                                                                                                                                                                                                                                                                                                                                                                                                    );
                                                                                                                                                                                                                                                                                                                                                                                                                    }