export default function Problem() {
      return (
          <section
                id="about"
                      className="bg-slate-50 px-6 py-24"
                          >
                                <div className="mx-auto max-w-6xl text-center">
                                        <p className="text-sm font-semibold uppercase tracking-[0.3em] text-orange-500">
                                                  THE PROBLEM
                                                          </p>

                                                                  <h2 className="mt-4 text-4xl font-bold text-slate-900">
                                                                            Most young builders never ship.
                                                                                    </h2>

                                                                                            <p className="mx-auto mt-6 max-w-3xl text-lg leading-8 text-slate-600">
                                                                                                      They collect ideas, watch tutorials, save posts, and wait for the
                                                                                                                perfect moment. Months pass, but nothing gets built.
                                                                                                                        </p>

                                                                                                                                <div className="mt-16 grid gap-8 md:grid-cols-3">
                                                                                                                                          <div className="rounded-2xl bg-white p-8 shadow-sm">
                                                                                                                                                      <div className="text-4xl">💡</div>
                                                                                                                                                                  <h3 className="mt-4 text-xl font-semibold">
                                                                                                                                                                                Too Many Ideas
                                                                                                                                                                                            </h3>
                                                                                                                                                                                                        <p className="mt-3 text-slate-600">
                                                                                                                                                                                                                      Endless brainstorming but no execution.
                                                                                                                                                                                                                                  </p>
                                                                                                                                                                                                                                            </div>

                                                                                                                                                                                                                                                      <div className="rounded-2xl bg-white p-8 shadow-sm">
                                                                                                                                                                                                                                                                  <div className="text-4xl">📚</div>
                                                                                                                                                                                                                                                                              <h3 className="mt-4 text-xl font-semibold">
                                                                                                                                                                                                                                                                                            Endless Learning
                                                                                                                                                                                                                                                                                                        </h3>
                                                                                                                                                                                                                                                                                                                    <p className="mt-3 text-slate-600">
                                                                                                                                                                                                                                                                                                                                  Tutorials replace real building experience.
                                                                                                                                                                                                                                                                                                                                              </p>
                                                                                                                                                                                                                                                                                                                                                        </div>

                                                                                                                                                                                                                                                                                                                                                                  <div className="rounded-2xl bg-white p-8 shadow-sm">
                                                                                                                                                                                                                                                                                                                                                                              <div className="text-4xl">🚧</div>
                                                                                                                                                                                                                                                                                                                                                                                          <h3 className="mt-4 text-xl font-semibold">
                                                                                                                                                                                                                                                                                                                                                                                                        No Accountability
                                                                                                                                                                                                                                                                                                                                                                                                                    </h3>
                                                                                                                                                                                                                                                                                                                                                                                                                                <p className="mt-3 text-slate-600">
                                                                                                                                                                                                                                                                                                                                                                                                                                              Without a community, projects quietly fade away.
                                                                                                                                                                                                                                                                                                                                                                                                                                                          </p>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                    </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                            </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      </section>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        );
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        }