export default function Solution() {
      return (
          <section className="bg-white px-6 py-24">
                <div className="mx-auto max-w-6xl">
                        <div className="text-center">
                                  <p className="text-sm font-semibold uppercase tracking-[0.3em] text-orange-500">
                                              THE SOLUTION
                                                        </p>

                                                                  <h2 className="mt-4 text-4xl font-bold text-slate-900">
                                                                              Builder Sprint
                                                                                        </h2>

                                                                                                  <p className="mx-auto mt-6 max-w-3xl text-lg leading-8 text-slate-600">
                                                                                                              A focused 14-day sprint where you stop consuming and start building.
                                                                                                                          Every day moves your project forward with clear tasks, community,
                                                                                                                                      and accountability.
                                                                                                                                                </p>
                                                                                                                                                        </div>

                                                                                                                                                                <div className="mt-16 grid gap-8 md:grid-cols-2">
                                                                                                                                                                          <div className="rounded-2xl border border-slate-200 p-8">
                                                                                                                                                                                      <h3 className="text-2xl font-bold text-slate-900">
                                                                                                                                                                                                    What you'll do
                                                                                                                                                                                                                </h3>

                                                                                                                                                                                                                            <ul className="mt-6 space-y-4 text-slate-600">
                                                                                                                                                                                                                                          <li>✅ Validate an idea</li>
                                                                                                                                                                                                                                                        <li>✅ Plan your MVP</li>
                                                                                                                                                                                                                                                                      <li>✅ Build consistently for 14 days</li>
                                                                                                                                                                                                                                                                                    <li>✅ Share progress publicly</li>
                                                                                                                                                                                                                                                                                                  <li>✅ Demo what you've built</li>
                                                                                                                                                                                                                                                                                                              </ul>
                                                                                                                                                                                                                                                                                                                        </div>

                                                                                                                                                                                                                                                                                                                                  <div className="rounded-2xl bg-orange-500 p-8 text-white">
                                                                                                                                                                                                                                                                                                                                              <h3 className="text-2xl font-bold">
                                                                                                                                                                                                                                                                                                                                                            By Day 14...
                                                                                                                                                                                                                                                                                                                                                                        </h3>

                                                                                                                                                                                                                                                                                                                                                                                    <p className="mt-6 leading-8">
                                                                                                                                                                                                                                                                                                                                                                                                  You'll have something real to show—not just another folder full of
                                                                                                                                                                                                                                                                                                                                                                                                                ideas or bookmarked tutorials.
                                                                                                                                                                                                                                                                                                                                                                                                                            </p>

                                                                                                                                                                                                                                                                                                                                                                                                                                        <div className="mt-8 rounded-xl bg-white/10 p-5">
                                                                                                                                                                                                                                                                                                                                                                                                                                                      <p className="font-semibold">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                      Build → Ship → Learn → Repeat
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    </p>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            </section>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              );
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              }